{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 16, in set2\n",
      "    if (second_input <= first_input):\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TypeError: '<=' not supported between instances of 'StringVar' and 'StringVar'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 16, in set2\n",
      "    if (second_input <= first_input):\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TypeError: '<=' not supported between instances of 'StringVar' and 'StringVar'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 16, in set2\n",
      "    if (second_input <= first_input):\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TypeError: '<=' not supported between instances of 'StringVar' and 'StringVar'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\widgets\\ctk_button.py\", line 554, in _clicked\n",
      "    self._command()\n",
      "  File \"C:\\Users\\saidk\\AppData\\Local\\Temp\\ipykernel_11740\\2540940976.py\", line 10, in set1\n",
      "    if (first_input < 0):\n",
      "        ^^^^^^^^^^^^^^^\n",
      "TypeError: '<' not supported between instances of 'StringVar' and 'int'\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[42], line 47\u001b[0m\n\u001b[0;32m     44\u001b[0m alarm_button2 \u001b[38;5;241m=\u001b[39m customtkinter\u001b[38;5;241m.\u001b[39mCTkButton(app, width\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m60\u001b[39m, height\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m30\u001b[39m, text\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSET\u001b[39m\u001b[38;5;124m\"\u001b[39m, command\u001b[38;5;241m=\u001b[39mset2)\n\u001b[0;32m     45\u001b[0m alarm_button2\u001b[38;5;241m.\u001b[39mgrid(row\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m3\u001b[39m, column\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m5\u001b[39m, padx\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m20\u001b[39m, pady\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m)\n\u001b[1;32m---> 47\u001b[0m \u001b[43mapp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmainloop\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\customtkinter\\windows\\ctk_tk.py:165\u001b[0m, in \u001b[0;36mCTk.mainloop\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    161\u001b[0m             \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdeiconify()\n\u001b[0;32m    163\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_window_exists \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m--> 165\u001b[0m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmainloop\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py:1504\u001b[0m, in \u001b[0;36mMisc.mainloop\u001b[1;34m(self, n)\u001b[0m\n\u001b[0;32m   1502\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mmainloop\u001b[39m(\u001b[38;5;28mself\u001b[39m, n\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m):\n\u001b[0;32m   1503\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Call the mainloop of Tk.\"\"\"\u001b[39;00m\n\u001b[1;32m-> 1504\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtk\u001b[38;5;241m.\u001b[39mmainloop(n)\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the current cell or a previous cell. \n",
      "\u001b[1;31mPlease review the code in the cell(s) to identify a possible cause of the failure. \n",
      "\u001b[1;31mClick <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "import tkinter\n",
    "import customtkinter\n",
    "\n",
    "\n",
    "\n",
    "customtkinter.set_appearance_mode(\"System\")\n",
    "customtkinter.set_default_color_theme(\"dark-blue\")\n",
    "\n",
    "def set1():\n",
    "    if first_input.get() < 0:\n",
    "        print(\"ERROR: INVALID VALUE\")\n",
    "    elif first_input.get() >= 0:\n",
    "        print(\"Alarm set to:\", first_input.get())\n",
    "\n",
    "def set2():\n",
    "    if second_input.get() <= first_input.get():\n",
    "        print(\"The second alarm cannot be lower than the first alarm\")\n",
    "    elif second_input.get() > first_input.get():\n",
    "        print(\"Alarm set to:\", second_input.get())\n",
    "\n",
    "\n",
    "app = customtkinter.CTk()\n",
    "app.geometry(\"800x480\")\n",
    "app.title(\"RET Demo Dashboard\")\n",
    "app.grid_columnconfigure(0, weight=1)\n",
    "app.grid_columnconfigure(1, weight=1)\n",
    "\n",
    "text1 = customtkinter.CTkLabel(app, text=\"Set First alarm\")\n",
    "text1.grid(row=0, column=3, padx=30, pady=0,)\n",
    "\n",
    "text1 = customtkinter.CTkLabel(app, text=\"Set second alarm\")\n",
    "text1.grid(row=2, column=3, padx=30, pady=0,)\n",
    "\n",
    "first_input = tkinter.DoubleVar()\n",
    "input1 = customtkinter.CTkEntry(app, width=100, height=30, textvariable=first_input)\n",
    "input1.grid(row=1, column=3, padx=20, pady=0)\n",
    "\n",
    "second_input = tkinter.DoubleVar()\n",
    "input2 = customtkinter.CTkEntry(app, width=100, height=30, textvariable=second_input)\n",
    "input2.grid(row=3, column=3, padx=20, pady=0)\n",
    "\n",
    "\n",
    "alarm_button1 = customtkinter.CTkButton(app, width=60, height=30, text=\"SET\", command=set1)\n",
    "alarm_button1.grid(row=1, column=5, padx=20, pady=0)\n",
    "\n",
    "alarm_button2 = customtkinter.CTkButton(app, width=60, height=30, text=\"SET\", command=set2)\n",
    "alarm_button2.grid(row=3, column=5, padx=20, pady=0)\n",
    "\n",
    "app.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
